Global parameters for the different number of hydro/mhd variables
ramses-organisation/ramses pull request #36
Opened 2024-10-28 16:26 UTC by tinecolman

Introduce `nvar_all`, `neul` and `nhydro` variables to simplify differences between MHD versus HYDRO. This allows for more general code and less preprocessor statements.

2024-11-01 11:27 UTC, nbrucy requested changes
This makes the counting of variable easier to understand, with no consequences for end user (maybe a very small performance loss due to moving some computation at runtime?)

Maybe this can be further improved by adding some developer documentation in `doc/dev_docs` explaining what are the different number of variables `nvar`, `nhydro`, `neul` (why not `neuler` btw?), `nvar_all`, `nener`, etc ... and how they can be used.

2024-11-01 11:27 UTC, nbrucy commented on mhd/hydro_parameters.f90
> +  integer,parameter::neul=5
Could neul be named neuler instead?

2024-11-01 11:27 UTC, nbrucy commented on mhd/hydro_parameters.f90
> +  ! total amount of variables
total amount of independent variables? (to distinguish from nvar_all)

2024-11-01 11:27 UTC, nbrucy commented on mhd/hydro_parameters.f90
> -  real(dp),dimension(1:NENER)::err_grad_prad=-1.0
Where are these gone?

2024-11-01 11:27 UTC, nbrucy commented on mhd/output_hydro.f90
> -                 w = uold(ind_grid(i)+iskip, 4)/d
Why are these changes relevant for the PR?

2024-11-04 09:17 UTC, tinecolman commented on mhd/hydro_parameters.f90
> +  integer,parameter::neul=5
I used neul because it was already used in some places in the code. I simple extended its use.

2024-11-04 09:19 UTC, nbrucy commented on mhd/hydro_parameters.f90
> +  integer,parameter::neul=5
Should we keep it like this?

2024-11-04 09:57 UTC, tinecolman commented on mhd/output_hydro.f90
> -                 w = uold(ind_grid(i)+iskip, 4)/d
Here I've synchronized the hydro and mhd version of the file. Reducing the amount of duplicate code between hydro and mhd was one of the motivations for introducing these new variables.

2024-11-04 09:58 UTC, cphyc commented on hydro/hydro_parameters.f90
> +  integer,parameter::nvar_all=nvar
Regarding @nbrucy's comment about performance, all the variables are defined as compile-time, so the compiler should optimise them as such. If truly this is a worry, one could also replace these definitions with compiler directives, i.e. in the Makefile, create `DEFINES = -DNVAR_all=[...] -Dnhydro=[...]` etc. and used capitalized form to distinguish from runtime params.

2024-11-04 10:01 UTC, tinecolman commented on mhd/hydro_parameters.f90
> -  real(dp),dimension(1:NENER)::err_grad_prad=-1.0
You mean err_grad_prad and err_grad_var? They are unused variables, so I removed them.

2024-11-04 10:05 UTC, tinecolman commented on mhd/hydro_parameters.f90
> +  integer,parameter::neul=5
In my opinion, neuler is not particulary more clear than neul. In any case, it is explained where the variable is defined. So I would opt for keeping neul.

2024-11-04 15:14 UTC, rteyssier commented on mhd/hydro_parameters.f90
> -  real(dp),dimension(1:NENER)::err_grad_prad=-1.0
They are unused but they could be used in the future or in a patch.
I would rather keep them.

2024-11-04 15:19 UTC, rteyssier requested changes
I would rather keep the radiation and passive scalar initial conditions and boundary conditions variables.

2024-11-15 14:40 UTC, tinecolman commented on hydro/hydro_parameters.f90
> +  integer,parameter::nvar_all=nvar
For nhydro it is there -DNHYDRO=$(NHYDRO). Should I add the others? I would think it is not an issue, but we don't really have performance tests in place that would cover the different configurations of these parameters so I can't know for sure.

2024-11-15 14:53 UTC, tinecolman commented on mhd/hydro_parameters.f90
> -  real(dp),dimension(1:NENER)::err_grad_prad=-1.0
I put them back.

2024-11-15 14:59 UTC, tinecolman commented on mhd/hydro_parameters.f90
> +  ! total amount of variables
Both nvar and nvar_all are total number of variables in a way...

2024-11-15 15:48 UTC, tinecolman commented
I've added some dev doc. Can be the start of a more detailed documentation on some implementation aspects.

2024-11-15 16:35 UTC, rteyssier approved these changes

2024-11-15 16:50 UTC, nbrucy approved these changes
I added the new doc page in the index and corrected some typos (see https://ramses-organisation--36.org.readthedocs.build/en/36/). Good for me!

2024-11-15 17:59 UTC, merged